[package]
name = "neura-studios/roact-rodux"
authors = ["Neura Studios", "EncodedLua"]
description = "Supports the functionality of Roblox/roact-rodux with some performance and QOL improvements"
version = "0.0.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.4"
Rodux = "roblox/rodux@3.0.0"
TestEZ = "roblox/testez@0.4.1"